version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: car_service
      POSTGRES_USER: car_service_user
      POSTGRES_PASSWORD: car_service_password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: ops/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pg_data:
