# Generated by Django 5.1.5 on 2025-01-30 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_customers_alter_car_color_alter_car_year_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
    ]
